[package]
name = "alexandria_macros"
version = "0.1.0"
description = "A set of useful macros"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/macros"
edition = "2024_07"

[cairo-plugin]

[tool]
fmt.workspace = true

[dev-dependencies]
assert_macros = "0.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.28.0" }

[scripts]
test = "snforge test"
test-profiling = "snforge test --build-profile"
