[package]
name = "alexandria_encoding"
version = "0.1.0"
description = "Encoding utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/encoding"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math" }
alexandria_numeric = { path = "../numeric" }
alexandria_bytes = { path = "../bytes" }

[dev-dependencies]
assert_macros = "0.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.28.0" }

[scripts]
test = "snforge test"
test-profiling = "snforge test --build-profile"
