[package]
name = "alexandria_data_structures"
version = "0.2.0"
description = "A set of Cairo data structure libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/data_structures"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
alexandria_encoding = { path = "../encoding" }

[dev-dependencies]
assert_macros = "0.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.28.0" }

[scripts]
test = "snforge test"
test-profiling = "snforge test --build-profile"
